name: "Deploy to cdn.geolonia.com"
inputs:
  cdn-deploy-command:
    description: "Command to run in cdn.geolonia.com"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: 'geolonia/cdn.geolonia.com'
        path: 'cdn.geolonia.com'

    - run: |
        echo "hi ${{ inputs.cdn-deploy-command }}"
        ls -lah ./cdn.geolonia.com
      shell: bash
